/*
 * This source file was generated by the Gradle 'init' task
 */
package csi2300;

public class App {
    public static String reverseString(String str) {
        String newStr = "";
        for (int i = str.length() - 1; i >= 0; i--) {
            newStr += str.charAt(i);
        }
        return newStr;
    }

    public static void main(String[] args) {
        try {
            System.out.println(reverseString(args[0]));
        } catch (java.lang.ArrayIndexOutOfBoundsException e) {
            System.out.println("ERROR: No string argument provided");
        }
    }
}
